DROP TABLE IF EXISTS TBL_WEBSHOP;

CREATE TABLE TBL_WEBSHOP {
id INT AUTO_INCEREMENT PRIMARY KEY,
product_name VARCHAR(250) NOT NULL,
product_description VARCHAR(250) NOT NULL,
product_stock SMALLINT(255) NOT NULL
};